#ifndef OPENCV_MODULES_HPP
#define OPENCV_MODULES_HPP
#define HAVE_OPENCV_CORE
#define HAVE_OPENCV_IMGPROC
#define HAVE_OPENCV_HIGHGUI
#define HAVE_OPENCV_IMGCODECS
#define HAVE_OPENCV_VIDEOIO
#define HAVE_OPENCV_PHOTO
#endif
